[package]
name = "stariver-adapter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lints.rust]
unsafe_code = "forbid"

[dependencies]
actix-web = { workspace = true }
actix-session = { workspace = true }
anyhow = { workspace = true }

chrono = { workspace = true }

sea-orm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

stariver-core = { path = "../stariver-core" }
uuid = { workspace = true }