[package]
name = "stariver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.3.1"
actix-web = "4.4.0"
actix-web-httpauth = "0.8.1"
actix-session = { version = "0.8.0", features = ["cookie-session"] }
argon2 = "0.5.2"
async_static = "0.1.3"
chrono = "0.4.31"
dotenvy = "0.15.7"
env_logger = "0.10.0"
# async_static
once_cell = "1.18.0"
sea-orm = { version = "0.12.3", features = ["debug-print", "sqlx-postgres", "runtime-tokio-rustls", "macros", "with-chrono"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"

[dependencies.uuid]
version = "1.4.1"
features = [
    "v4", # Lets you generate random UUIDs
    "fast-rng", # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]
