[package]
name = "stariver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lints.rust]
unsafe_code = "forbid"

[profile.dev]
opt-level = 0
# Set the default for dependencies.
[profile.dev.package."*"]
opt-level = 0

[dependencies]
ferris-says = "0.3.1"
actix-web = "4.4.1"
actix-web-httpauth = "0.8.1"
actix-session = { version = "0.9.0", features = ["cookie-session"] }
argon2 = "0.5.3"
async_static = "0.1.3"
chrono = "0.4.33"
dotenvy = "0.15.7"
env_logger = "0.11.1"
# async_static
once_cell = "1.19.0"
sea-orm = { version = "0.12.12", features = ["debug-print", "sqlx-postgres", "runtime-tokio-rustls", "macros", "with-chrono"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.112"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[dependencies.uuid]
version = "1.7.0"
features = [
    "v7", # Lets you generate random UUIDs
    "fast-rng", # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]
