[workspace]
resolver = "2"
members = [
    "crates/stariver",
    "crates/stariver-adapter",
    "crates/stariver-core",
]

[workspace.dependencies]
actix-web = "^4"
actix-web-httpauth = "^0"
actix-session = { version = "^0", features = ["cookie-session"] }
anyhow = "1.0"
chrono = "^0"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
sea-orm = { version = "^0", features = ["debug-print", "sqlx-postgres", "runtime-tokio-rustls", "macros", "with-chrono"] }
uuid = { version = "^1", features = ["v7", "fast-rng", "macro-diagnostics"] }

[profile.dev]
opt-level = 0
# Set the default for dependencies.
[profile.dev.package."*"]
opt-level = 0