[package]
name = "stariver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.3.1"
actix-web = "4.3.1"
actix-files = "0.6.2"
actix-session = { version="0.7.2", features = ["cookie-session"]}
env_logger = "0.10.0"
sea-orm = { version = "0.11.3", features = ["debug-print", "sqlx-postgres", "runtime-actix-rustls", "macros", "with-chrono"] }
serde = { version = "1.0.164", features = ["derive"] }
chrono = "0.4.26"
async-std = "1.12.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"

[dependencies.uuid]
version = "1.4.1"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]
