[workspace]
resolver = "2"
members = [
    "crates/stariver-adapter",
    "crates/stariver-core",
]

[workspace.dependencies]
ferris-says = "^0.3.1"

[profile.dev]
opt-level = 0
# Set the default for dependencies.
[profile.dev.package."*"]
opt-level = 0