[package]
name = "stariver-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lints.rust]
unsafe_code = "forbid"

[dependencies]
actix-web = "^4.5.1"
actix-web-httpauth = "^0.8.1"
actix-session = { version = "^0.9.0", features = ["cookie-session"] }

argon2 = "^0.5.3"
async_static = "^0.1.3"
chrono = "^0.4.33"
dotenvy = "^0.15.7"
env_logger = "^0.11.1"
# async_static
once_cell = "^1.19.0"
sea-orm = { version = "^0.12.12", features = ["debug-print", "sqlx-postgres", "runtime-tokio-rustls", "macros", "with-chrono"] }
serde = { version = "^1.0.196", features = ["derive"] }
serde_json = "^1.0.113"
trait-variant = "0.1.1"
tracing = "^0.1.40"
tracing-subscriber = "^0.3.18"
uuid = { version = "^1.7.0", features = ["v7", "fast-rng", "macro-diagnostics"] }