[package]
name = "stariver-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lints.rust]
unsafe_code = "forbid"

[dependencies]
actix-web = "^4"
actix-web-httpauth = "^0"
actix-session = { version = "^0", features = ["cookie-session"] }

argon2 = "^0"
async_static = "^0"
chrono = "^0"
dotenvy = "^0"
env_logger = "^0"
# async_static
once_cell = "^1"
sea-orm = { version = "^0", features = ["debug-print", "sqlx-postgres", "runtime-tokio-rustls", "macros", "with-chrono"] }
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
trait-variant = "^0"
tracing = "^0"
tracing-subscriber = "^0"
uuid = { version = "^1", features = ["v7", "fast-rng", "macro-diagnostics"] }